[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-traits = { workspace = true }
itertools = "0.13.0"


[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
