[package]
name = "day11"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-traits = { workspace = true }
memoize = "0.4.2"


[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
